Github actions:  Build shared always on shared changes, not just on TAG releases (#1058)
* Fixed error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment
    Error: Process completed with exit code 2.

* - some change just to check if it works
- pre-commit hook incerase ruff to v0.15.0

* - Build shared always on shared changes, not just on TAG releases
- small doc change to see if it works

* small update

---------

Co-authored-by: Jan Polonsky <jan.polonsky@nbu.gov.sk>