Logging improvement part 2. (Collectors) Fixed: AttributeError: 'WebDriver' object has no attribute 'dispose' Tidy up log types Same logs for each collector (start, finish) moved to one place