User settings (#867)
* Add support for settings_user table
* Removed unused profile releated tables
* Ruff checks
* Fixed news item text highlighting for dark theme
* Fixed some issues with new user settings functionality
* Fixed jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'baseScore' - added default values for empty CVSS
* Added new user setting: Show source link in news items (default True)
* Some small source refactoring
* Fixed: On Agregate news items was displayed html content instead of text
* slightly change setting name
* small typo