- Fixed: AttributeError: 'NoneType' object has no attribute 'news_item_data'. It was caused by showItemDetail in NewsItemSelector where was send wrong parameter. Now is called child event that emit correct parameter - Tidy up code in NewReportItem